"""create all remaining tables

Revision ID: 070a46c0ce90
Revises: 0bdcada56da3
Create Date: 2026-04-23 10:34:21.849510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070a46c0ce90'
down_revision: Union[str, Sequence[str], None] = '0bdcada56da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivo_iot',
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('codigo_serie', sa.String(length=50), nullable=False),
    sa.Column('nome_dispositivo', sa.String(length=100), nullable=True),
    sa.Column('status_dispositivo', sa.String(length=30), nullable=True),
    sa.Column('data_ativacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_comunicacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wifi_configurado', sa.Boolean(), nullable=True),
    sa.Column('local_instalacao', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_dispositivo'),
    sa.UniqueConstraint('codigo_serie')
    )
    op.create_table('bomba_dagua',
    sa.Column('id_bomba', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('tipo_bomba', sa.String(length=50), nullable=True),
    sa.Column('vazao', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status_bomba', sa.String(length=30), nullable=True),
    sa.Column('data_instalacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo_iot.id_dispositivo'], ),
    sa.PrimaryKeyConstraint('id_bomba')
    )
    op.create_table('cronograma_cuidado',
    sa.Column('id_cronograma', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('data_geracao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('descricao_resumida', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.PrimaryKeyConstraint('id_cronograma')
    )
    op.create_table('historico_cuidado',
    sa.Column('id_historico', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('descricao_evento', sa.Text(), nullable=False),
    sa.Column('data_hora_evento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('origem_evento', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    op.create_table('notificacao',
    sa.Column('id_notificacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=True),
    sa.Column('tipo_notificacao', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lida', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('canal_envio', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacao')
    )
    op.create_table('recomendacao_ia',
    sa.Column('id_recomendacao', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('data_geracao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_recomendacao', sa.String(length=50), nullable=True),
    sa.Column('descricao_recomendacao', sa.Text(), nullable=False),
    sa.Column('nivel_prioridade', sa.String(length=20), nullable=True),
    sa.Column('status_recomendacao', sa.String(length=30), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.PrimaryKeyConstraint('id_recomendacao')
    )
    op.create_table('sensor_umidade',
    sa.Column('id_sensor', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('tipo_sensor', sa.String(length=50), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.Column('status_sensor', sa.String(length=30), nullable=True),
    sa.Column('data_instalacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calibracao_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calibracao_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo_iot.id_dispositivo'], ),
    sa.PrimaryKeyConstraint('id_sensor')
    )
    op.create_table('vinculo_planta_dispositivo',
    sa.Column('id_vinculo', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo_iot.id_dispositivo'], ),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.PrimaryKeyConstraint('id_vinculo')
    )
    op.create_table('irrigacao',
    sa.Column('id_irrigacao', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('id_bomba', sa.Integer(), nullable=False),
    sa.Column('tipo_irrigacao', sa.String(length=20), nullable=False),
    sa.Column('origem_decisao', sa.String(length=30), nullable=True),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracao_segundos', sa.Integer(), nullable=True),
    sa.Column('volume_estimado', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status_execucao', sa.String(length=30), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_bomba'], ['bomba_dagua.id_bomba'], ),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo_iot.id_dispositivo'], ),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.PrimaryKeyConstraint('id_irrigacao')
    )
    op.create_table('item_cronograma',
    sa.Column('id_item_cronograma', sa.Integer(), nullable=False),
    sa.Column('id_cronograma', sa.Integer(), nullable=False),
    sa.Column('tipo_cuidado', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_prevista', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_execucao', sa.String(length=30), nullable=True),
    sa.Column('data_execucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origem_item', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_cronograma'], ['cronograma_cuidado.id_cronograma'], ),
    sa.PrimaryKeyConstraint('id_item_cronograma')
    )
    op.create_table('leitura_umidade',
    sa.Column('id_leitura', sa.Integer(), nullable=False),
    sa.Column('id_sensor', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('valor_umidade', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_hora_leitura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_leitura', sa.String(length=30), nullable=True),
    sa.Column('origem_leitura', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.ForeignKeyConstraint(['id_sensor'], ['sensor_umidade.id_sensor'], ),
    sa.PrimaryKeyConstraint('id_leitura')
    )
    op.alter_column('plantas', 'ativa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plantas', 'ativa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_table('leitura_umidade')
    op.drop_table('item_cronograma')
    op.drop_table('irrigacao')
    op.drop_table('vinculo_planta_dispositivo')
    op.drop_table('sensor_umidade')
    op.drop_table('recomendacao_ia')
    op.drop_table('notificacao')
    op.drop_table('historico_cuidado')
    op.drop_table('cronograma_cuidado')
    op.drop_table('bomba_dagua')
    op.drop_table('dispositivo_iot')
    # ### end Alembic commands ###
