"""create plantas table

Revision ID: 0bdcada56da3
Revises: 6a7d3a6b98de
Create Date: 2026-04-23 10:06:48.664263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdcada56da3'
down_revision: Union[str, Sequence[str], None] = '6a7d3a6b98de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantas',
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_especie', sa.Integer(), nullable=False),
    sa.Column('nome_personalizado', sa.String(length=100), nullable=True),
    sa.Column('porte', sa.String(length=30), nullable=True),
    sa.Column('ambiente', sa.String(length=50), nullable=True),
    sa.Column('localizacao_descricao', sa.String(length=200), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(
        ['id_especie'],
        ['especies.id_especie'],
        name='fk_plantas_especie'
    ),
    sa.ForeignKeyConstraint(
        ['id_usuario'],
        ['usuarios.id_usuario'],
        name='fk_plantas_usuario'
    ),
    sa.PrimaryKeyConstraint('id_planta')
    )
    op.create_index(op.f('ix_plantas_id_planta'), 'plantas', ['id_planta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plantas_id_planta'), table_name='plantas')
    op.drop_table('plantas')
    # ### end Alembic commands ###
