"""create especies table

Revision ID: 6a7d3a6b98de
Revises: 75c1d7e6291f
Create Date: 2026-04-23 10:03:45.888569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7d3a6b98de'
down_revision: Union[str, Sequence[str], None] = '75c1d7e6291f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especies',
    sa.Column('id_especie', sa.Integer(), nullable=False),
    sa.Column('nome_comum', sa.String(length=100), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('faixa_umidade_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('faixa_umidade_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frequencia_media_irrigacao', sa.Integer(), nullable=True),
    sa.Column('necessidade_luz', sa.String(length=50), nullable=True),
    sa.Column('observacoes_cuidado', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_especie')
    )
    op.create_index(op.f('ix_especies_id_especie'), 'especies', ['id_especie'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_especies_id_especie'), table_name='especies')
    op.drop_table('especies')
    # ### end Alembic commands ###
