"""add_leitura_sensor_evento_irrigacao_comando_irrigacao

Revision ID: 93cc187eda7c
Revises: 070a46c0ce90
Create Date: 2026-06-09 10:15:26.180616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cc187eda7c'
down_revision: Union[str, Sequence[str], None] = '070a46c0ce90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comando_irrigacao',
    sa.Column('id_comando', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('pendente', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.PrimaryKeyConstraint('id_comando')
    )
    op.create_index(op.f('ix_comando_irrigacao_id_planta'), 'comando_irrigacao', ['id_planta'], unique=False)
    op.create_table('evento_irrigacao',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('duracao_segundos', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index(op.f('ix_evento_irrigacao_id_planta'), 'evento_irrigacao', ['id_planta'], unique=False)
    op.create_table('leitura_sensor',
    sa.Column('id_leitura', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.Column('umidade_percentual', sa.Float(), nullable=False),
    sa.Column('adc_bruto', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_planta'], ['plantas.id_planta'], ),
    sa.PrimaryKeyConstraint('id_leitura')
    )
    op.create_index(op.f('ix_leitura_sensor_id_planta'), 'leitura_sensor', ['id_planta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leitura_sensor_id_planta'), table_name='leitura_sensor')
    op.drop_table('leitura_sensor')
    op.drop_index(op.f('ix_evento_irrigacao_id_planta'), table_name='evento_irrigacao')
    op.drop_table('evento_irrigacao')
    op.drop_index(op.f('ix_comando_irrigacao_id_planta'), table_name='comando_irrigacao')
    op.drop_table('comando_irrigacao')
    # ### end Alembic commands ###
